services:
  - type: web
    name: bakelit-songs
    env: node
    plan: free
    rootDir: .
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: TO_EMAIL
        sync: false
      - key: MAIL_FROM
        sync: false
